services:
  pg:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: "yuspavel"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: "wether"
    ports:
      - "54321:5432"